services:
  - type: web
    name: itelect-gt2b-marketplace
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: JWT_COOKIE_EXPIRES_IN
        value: 90
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: 2525
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
